// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bizmock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/internal/biz"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTodoRepo creates a new instance of MockTodoRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepo {
	mock := &MockTodoRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoRepo is an autogenerated mock type for the TodoRepo type
type MockTodoRepo struct {
	mock.Mock
}

type MockTodoRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepo) EXPECT() *MockTodoRepo_Expecter {
	return &MockTodoRepo_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodoRepo
func (_mock *MockTodoRepo) CreateTodo(context1 context.Context, todo *biz.Todo) (*biz.Todo, error) {
	ret := _mock.Called(context1, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *biz.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.Todo) (*biz.Todo, error)); ok {
		return returnFunc(context1, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.Todo) *biz.Todo); ok {
		r0 = returnFunc(context1, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *biz.Todo) error); ok {
		r1 = returnFunc(context1, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepo_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoRepo_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - todo *biz.Todo
func (_e *MockTodoRepo_Expecter) CreateTodo(context1 any, todo any) *MockTodoRepo_CreateTodo_Call {
	return &MockTodoRepo_CreateTodo_Call{Call: _e.mock.On("CreateTodo", context1, todo)}
}

func (_c *MockTodoRepo_CreateTodo_Call) Run(run func(context1 context.Context, todo *biz.Todo)) *MockTodoRepo_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.Todo
		if args[1] != nil {
			arg1 = args[1].(*biz.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepo_CreateTodo_Call) Return(todo1 *biz.Todo, err error) *MockTodoRepo_CreateTodo_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodoRepo_CreateTodo_Call) RunAndReturn(run func(context1 context.Context, todo *biz.Todo) (*biz.Todo, error)) *MockTodoRepo_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodoRepo
func (_mock *MockTodoRepo) DeleteTodo(context1 context.Context, n int64) error {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(context1, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepo_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoRepo_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockTodoRepo_Expecter) DeleteTodo(context1 any, n any) *MockTodoRepo_DeleteTodo_Call {
	return &MockTodoRepo_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", context1, n)}
}

func (_c *MockTodoRepo_DeleteTodo_Call) Run(run func(context1 context.Context, n int64)) *MockTodoRepo_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepo_DeleteTodo_Call) Return(err error) *MockTodoRepo_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepo_DeleteTodo_Call) RunAndReturn(run func(context1 context.Context, n int64) error) *MockTodoRepo_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTodoRepo
func (_mock *MockTodoRepo) FindByID(context1 context.Context, n int64) (*biz.Todo, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *biz.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*biz.Todo, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *biz.Todo); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTodoRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockTodoRepo_Expecter) FindByID(context1 any, n any) *MockTodoRepo_FindByID_Call {
	return &MockTodoRepo_FindByID_Call{Call: _e.mock.On("FindByID", context1, n)}
}

func (_c *MockTodoRepo_FindByID_Call) Run(run func(context1 context.Context, n int64)) *MockTodoRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepo_FindByID_Call) Return(todo *biz.Todo, err error) *MockTodoRepo_FindByID_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoRepo_FindByID_Call) RunAndReturn(run func(context1 context.Context, n int64) (*biz.Todo, error)) *MockTodoRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockTodoRepo
func (_mock *MockTodoRepo) ListTodos(context1 context.Context, listOptions ...biz.ListOption) ([]*biz.Todo, error) {
	var tmpRet mock.Arguments
	if len(listOptions) > 0 {
		tmpRet = _mock.Called(context1, listOptions)
	} else {
		tmpRet = _mock.Called(context1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 []*biz.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...biz.ListOption) ([]*biz.Todo, error)); ok {
		return returnFunc(context1, listOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...biz.ListOption) []*biz.Todo); ok {
		r0 = returnFunc(context1, listOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...biz.ListOption) error); ok {
		r1 = returnFunc(context1, listOptions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepo_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoRepo_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - context1 context.Context
//   - listOptions ...biz.ListOption
func (_e *MockTodoRepo_Expecter) ListTodos(context1 any, listOptions ...any) *MockTodoRepo_ListTodos_Call {
	return &MockTodoRepo_ListTodos_Call{Call: _e.mock.On("ListTodos",
		append([]any{context1}, listOptions...)...)}
}

func (_c *MockTodoRepo_ListTodos_Call) Run(run func(context1 context.Context, listOptions ...biz.ListOption)) *MockTodoRepo_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []biz.ListOption
		var variadicArgs []biz.ListOption
		if len(args) > 1 {
			variadicArgs = args[1].([]biz.ListOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTodoRepo_ListTodos_Call) Return(todos []*biz.Todo, err error) *MockTodoRepo_ListTodos_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockTodoRepo_ListTodos_Call) RunAndReturn(run func(context1 context.Context, listOptions ...biz.ListOption) ([]*biz.Todo, error)) *MockTodoRepo_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoRepo
func (_mock *MockTodoRepo) UpdateTodo(context1 context.Context, todo *biz.Todo) (*biz.Todo, error) {
	ret := _mock.Called(context1, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *biz.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.Todo) (*biz.Todo, error)); ok {
		return returnFunc(context1, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.Todo) *biz.Todo); ok {
		r0 = returnFunc(context1, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *biz.Todo) error); ok {
		r1 = returnFunc(context1, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepo_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoRepo_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - todo *biz.Todo
func (_e *MockTodoRepo_Expecter) UpdateTodo(context1 any, todo any) *MockTodoRepo_UpdateTodo_Call {
	return &MockTodoRepo_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", context1, todo)}
}

func (_c *MockTodoRepo_UpdateTodo_Call) Run(run func(context1 context.Context, todo *biz.Todo)) *MockTodoRepo_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.Todo
		if args[1] != nil {
			arg1 = args[1].(*biz.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepo_UpdateTodo_Call) Return(todo1 *biz.Todo, err error) *MockTodoRepo_UpdateTodo_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodoRepo_UpdateTodo_Call) RunAndReturn(run func(context1 context.Context, todo *biz.Todo) (*biz.Todo, error)) *MockTodoRepo_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}
