// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockTodoService_WatchTodosServer creates a new instance of MockTodoService_WatchTodosServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoService_WatchTodosServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoService_WatchTodosServer {
	mock := &MockTodoService_WatchTodosServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoService_WatchTodosServer is an autogenerated mock type for the TodoService_WatchTodosServer type
type MockTodoService_WatchTodosServer struct {
	mock.Mock
}

type MockTodoService_WatchTodosServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoService_WatchTodosServer) EXPECT() *MockTodoService_WatchTodosServer_Expecter {
	return &MockTodoService_WatchTodosServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockTodoService_WatchTodosServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockTodoService_WatchTodosServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockTodoService_WatchTodosServer_Expecter) Context() *MockTodoService_WatchTodosServer_Context_Call {
	return &MockTodoService_WatchTodosServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockTodoService_WatchTodosServer_Context_Call) Run(run func()) *MockTodoService_WatchTodosServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_Context_Call) Return(context1 context.Context) *MockTodoService_WatchTodosServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockTodoService_WatchTodosServer_Context_Call) RunAndReturn(run func() context.Context) *MockTodoService_WatchTodosServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_WatchTodosServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockTodoService_WatchTodosServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockTodoService_WatchTodosServer_Expecter) RecvMsg(m any) *MockTodoService_WatchTodosServer_RecvMsg_Call {
	return &MockTodoService_WatchTodosServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockTodoService_WatchTodosServer_RecvMsg_Call) Run(run func(m any)) *MockTodoService_WatchTodosServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_RecvMsg_Call) Return(err error) *MockTodoService_WatchTodosServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_WatchTodosServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockTodoService_WatchTodosServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) Send(todoEvent *v1.TodoEvent) error {
	ret := _mock.Called(todoEvent)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*v1.TodoEvent) error); ok {
		r0 = returnFunc(todoEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_WatchTodosServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTodoService_WatchTodosServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - todoEvent *v1.TodoEvent
func (_e *MockTodoService_WatchTodosServer_Expecter) Send(todoEvent any) *MockTodoService_WatchTodosServer_Send_Call {
	return &MockTodoService_WatchTodosServer_Send_Call{Call: _e.mock.On("Send", todoEvent)}
}

func (_c *MockTodoService_WatchTodosServer_Send_Call) Run(run func(todoEvent *v1.TodoEvent)) *MockTodoService_WatchTodosServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.TodoEvent
		if args[0] != nil {
			arg0 = args[0].(*v1.TodoEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_Send_Call) Return(err error) *MockTodoService_WatchTodosServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_WatchTodosServer_Send_Call) RunAndReturn(run func(todoEvent *v1.TodoEvent) error) *MockTodoService_WatchTodosServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_WatchTodosServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockTodoService_WatchTodosServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockTodoService_WatchTodosServer_Expecter) SendHeader(mD any) *MockTodoService_WatchTodosServer_SendHeader_Call {
	return &MockTodoService_WatchTodosServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockTodoService_WatchTodosServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockTodoService_WatchTodosServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SendHeader_Call) Return(err error) *MockTodoService_WatchTodosServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockTodoService_WatchTodosServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_WatchTodosServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockTodoService_WatchTodosServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockTodoService_WatchTodosServer_Expecter) SendMsg(m any) *MockTodoService_WatchTodosServer_SendMsg_Call {
	return &MockTodoService_WatchTodosServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockTodoService_WatchTodosServer_SendMsg_Call) Run(run func(m any)) *MockTodoService_WatchTodosServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SendMsg_Call) Return(err error) *MockTodoService_WatchTodosServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockTodoService_WatchTodosServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_WatchTodosServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockTodoService_WatchTodosServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockTodoService_WatchTodosServer_Expecter) SetHeader(mD any) *MockTodoService_WatchTodosServer_SetHeader_Call {
	return &MockTodoService_WatchTodosServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockTodoService_WatchTodosServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockTodoService_WatchTodosServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SetHeader_Call) Return(err error) *MockTodoService_WatchTodosServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockTodoService_WatchTodosServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockTodoService_WatchTodosServer
func (_mock *MockTodoService_WatchTodosServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockTodoService_WatchTodosServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockTodoService_WatchTodosServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockTodoService_WatchTodosServer_Expecter) SetTrailer(mD any) *MockTodoService_WatchTodosServer_SetTrailer_Call {
	return &MockTodoService_WatchTodosServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockTodoService_WatchTodosServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockTodoService_WatchTodosServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SetTrailer_Call) Return() *MockTodoService_WatchTodosServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTodoService_WatchTodosServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockTodoService_WatchTodosServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
