// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockTodoService_SyncTodosClient creates a new instance of MockTodoService_SyncTodosClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoService_SyncTodosClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoService_SyncTodosClient {
	mock := &MockTodoService_SyncTodosClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoService_SyncTodosClient is an autogenerated mock type for the TodoService_SyncTodosClient type
type MockTodoService_SyncTodosClient struct {
	mock.Mock
}

type MockTodoService_SyncTodosClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoService_SyncTodosClient) EXPECT() *MockTodoService_SyncTodosClient_Expecter {
	return &MockTodoService_SyncTodosClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockTodoService_SyncTodosClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosClient_Expecter) CloseSend() *MockTodoService_SyncTodosClient_CloseSend_Call {
	return &MockTodoService_SyncTodosClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockTodoService_SyncTodosClient_CloseSend_Call) Run(run func()) *MockTodoService_SyncTodosClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_CloseSend_Call) Return(err error) *MockTodoService_SyncTodosClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_CloseSend_Call) RunAndReturn(run func() error) *MockTodoService_SyncTodosClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockTodoService_SyncTodosClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockTodoService_SyncTodosClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosClient_Expecter) Context() *MockTodoService_SyncTodosClient_Context_Call {
	return &MockTodoService_SyncTodosClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockTodoService_SyncTodosClient_Context_Call) Run(run func()) *MockTodoService_SyncTodosClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Context_Call) Return(context1 context.Context) *MockTodoService_SyncTodosClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Context_Call) RunAndReturn(run func() context.Context) *MockTodoService_SyncTodosClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoService_SyncTodosClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockTodoService_SyncTodosClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosClient_Expecter) Header() *MockTodoService_SyncTodosClient_Header_Call {
	return &MockTodoService_SyncTodosClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockTodoService_SyncTodosClient_Header_Call) Run(run func()) *MockTodoService_SyncTodosClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Header_Call) Return(mD metadata.MD, err error) *MockTodoService_SyncTodosClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockTodoService_SyncTodosClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) Recv() (*v1.TodoEvent, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *v1.TodoEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*v1.TodoEvent, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *v1.TodoEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.TodoEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoService_SyncTodosClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockTodoService_SyncTodosClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosClient_Expecter) Recv() *MockTodoService_SyncTodosClient_Recv_Call {
	return &MockTodoService_SyncTodosClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockTodoService_SyncTodosClient_Recv_Call) Run(run func()) *MockTodoService_SyncTodosClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Recv_Call) Return(todoEvent *v1.TodoEvent, err error) *MockTodoService_SyncTodosClient_Recv_Call {
	_c.Call.Return(todoEvent, err)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Recv_Call) RunAndReturn(run func() (*v1.TodoEvent, error)) *MockTodoService_SyncTodosClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockTodoService_SyncTodosClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockTodoService_SyncTodosClient_Expecter) RecvMsg(m any) *MockTodoService_SyncTodosClient_RecvMsg_Call {
	return &MockTodoService_SyncTodosClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockTodoService_SyncTodosClient_RecvMsg_Call) Run(run func(m any)) *MockTodoService_SyncTodosClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_RecvMsg_Call) Return(err error) *MockTodoService_SyncTodosClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockTodoService_SyncTodosClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) Send(syncTodoRequest *v1.SyncTodoRequest) error {
	ret := _mock.Called(syncTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*v1.SyncTodoRequest) error); ok {
		r0 = returnFunc(syncTodoRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTodoService_SyncTodosClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - syncTodoRequest *v1.SyncTodoRequest
func (_e *MockTodoService_SyncTodosClient_Expecter) Send(syncTodoRequest any) *MockTodoService_SyncTodosClient_Send_Call {
	return &MockTodoService_SyncTodosClient_Send_Call{Call: _e.mock.On("Send", syncTodoRequest)}
}

func (_c *MockTodoService_SyncTodosClient_Send_Call) Run(run func(syncTodoRequest *v1.SyncTodoRequest)) *MockTodoService_SyncTodosClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.SyncTodoRequest
		if args[0] != nil {
			arg0 = args[0].(*v1.SyncTodoRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Send_Call) Return(err error) *MockTodoService_SyncTodosClient_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Send_Call) RunAndReturn(run func(syncTodoRequest *v1.SyncTodoRequest) error) *MockTodoService_SyncTodosClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockTodoService_SyncTodosClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockTodoService_SyncTodosClient_Expecter) SendMsg(m any) *MockTodoService_SyncTodosClient_SendMsg_Call {
	return &MockTodoService_SyncTodosClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockTodoService_SyncTodosClient_SendMsg_Call) Run(run func(m any)) *MockTodoService_SyncTodosClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_SendMsg_Call) Return(err error) *MockTodoService_SyncTodosClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_SendMsg_Call) RunAndReturn(run func(m any) error) *MockTodoService_SyncTodosClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockTodoService_SyncTodosClient
func (_mock *MockTodoService_SyncTodosClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockTodoService_SyncTodosClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockTodoService_SyncTodosClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosClient_Expecter) Trailer() *MockTodoService_SyncTodosClient_Trailer_Call {
	return &MockTodoService_SyncTodosClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockTodoService_SyncTodosClient_Trailer_Call) Run(run func()) *MockTodoService_SyncTodosClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Trailer_Call) Return(mD metadata.MD) *MockTodoService_SyncTodosClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockTodoService_SyncTodosClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockTodoService_SyncTodosClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}
