// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/go-kratos/kratos/v3/transport/http"
	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockTodoServiceHTTPClient creates a new instance of MockTodoServiceHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoServiceHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoServiceHTTPClient {
	mock := &MockTodoServiceHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoServiceHTTPClient is an autogenerated mock type for the TodoServiceHTTPClient type
type MockTodoServiceHTTPClient struct {
	mock.Mock
}

type MockTodoServiceHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoServiceHTTPClient) EXPECT() *MockTodoServiceHTTPClient_Expecter {
	return &MockTodoServiceHTTPClient_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) CreateTodo(ctx context.Context, req *v1.CreateTodoRequest, opts ...http.CallOption) (*v1.Todo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest, ...http.CallOption) (*v1.Todo, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest, ...http.CallOption) *v1.Todo); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.CreateTodoRequest, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoServiceHTTPClient_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v1.CreateTodoRequest
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) CreateTodo(ctx any, req any, opts ...any) *MockTodoServiceHTTPClient_CreateTodo_Call {
	return &MockTodoServiceHTTPClient_CreateTodo_Call{Call: _e.mock.On("CreateTodo",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_CreateTodo_Call) Run(run func(ctx context.Context, req *v1.CreateTodoRequest, opts ...http.CallOption)) *MockTodoServiceHTTPClient_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.CreateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.CreateTodoRequest)
		}
		var arg2 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]http.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_CreateTodo_Call) Return(rsp *v1.Todo, err error) *MockTodoServiceHTTPClient_CreateTodo_Call {
	_c.Call.Return(rsp, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, req *v1.CreateTodoRequest, opts ...http.CallOption) (*v1.Todo, error)) *MockTodoServiceHTTPClient_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) DeleteTodo(ctx context.Context, req *v1.DeleteTodoRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest, ...http.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest, ...http.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.DeleteTodoRequest, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoServiceHTTPClient_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v1.DeleteTodoRequest
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) DeleteTodo(ctx any, req any, opts ...any) *MockTodoServiceHTTPClient_DeleteTodo_Call {
	return &MockTodoServiceHTTPClient_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_DeleteTodo_Call) Run(run func(ctx context.Context, req *v1.DeleteTodoRequest, opts ...http.CallOption)) *MockTodoServiceHTTPClient_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.DeleteTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.DeleteTodoRequest)
		}
		var arg2 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]http.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_DeleteTodo_Call) Return(rsp *emptypb.Empty, err error) *MockTodoServiceHTTPClient_DeleteTodo_Call {
	_c.Call.Return(rsp, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, req *v1.DeleteTodoRequest, opts ...http.CallOption) (*emptypb.Empty, error)) *MockTodoServiceHTTPClient_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) GetTodo(ctx context.Context, req *v1.GetTodoRequest, opts ...http.CallOption) (*v1.Todo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest, ...http.CallOption) (*v1.Todo, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest, ...http.CallOption) *v1.Todo); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.GetTodoRequest, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodoServiceHTTPClient_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v1.GetTodoRequest
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) GetTodo(ctx any, req any, opts ...any) *MockTodoServiceHTTPClient_GetTodo_Call {
	return &MockTodoServiceHTTPClient_GetTodo_Call{Call: _e.mock.On("GetTodo",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_GetTodo_Call) Run(run func(ctx context.Context, req *v1.GetTodoRequest, opts ...http.CallOption)) *MockTodoServiceHTTPClient_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.GetTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.GetTodoRequest)
		}
		var arg2 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]http.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_GetTodo_Call) Return(rsp *v1.Todo, err error) *MockTodoServiceHTTPClient_GetTodo_Call {
	_c.Call.Return(rsp, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_GetTodo_Call) RunAndReturn(run func(ctx context.Context, req *v1.GetTodoRequest, opts ...http.CallOption) (*v1.Todo, error)) *MockTodoServiceHTTPClient_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) ListTodos(ctx context.Context, req *v1.ListTodosRequest, opts ...http.CallOption) (*v1.TodoSet, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 *v1.TodoSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest, ...http.CallOption) (*v1.TodoSet, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest, ...http.CallOption) *v1.TodoSet); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.TodoSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ListTodosRequest, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoServiceHTTPClient_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v1.ListTodosRequest
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) ListTodos(ctx any, req any, opts ...any) *MockTodoServiceHTTPClient_ListTodos_Call {
	return &MockTodoServiceHTTPClient_ListTodos_Call{Call: _e.mock.On("ListTodos",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_ListTodos_Call) Run(run func(ctx context.Context, req *v1.ListTodosRequest, opts ...http.CallOption)) *MockTodoServiceHTTPClient_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ListTodosRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ListTodosRequest)
		}
		var arg2 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]http.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_ListTodos_Call) Return(rsp *v1.TodoSet, err error) *MockTodoServiceHTTPClient_ListTodos_Call {
	_c.Call.Return(rsp, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_ListTodos_Call) RunAndReturn(run func(ctx context.Context, req *v1.ListTodosRequest, opts ...http.CallOption) (*v1.TodoSet, error)) *MockTodoServiceHTTPClient_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// SyncTodos provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) SyncTodos(ctx context.Context, opts ...http.CallOption) (v1.TodoService_SyncTodosClient, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SyncTodos")
	}

	var r0 v1.TodoService_SyncTodosClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...http.CallOption) (v1.TodoService_SyncTodosClient, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...http.CallOption) v1.TodoService_SyncTodosClient); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.TodoService_SyncTodosClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_SyncTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncTodos'
type MockTodoServiceHTTPClient_SyncTodos_Call struct {
	*mock.Call
}

// SyncTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) SyncTodos(ctx any, opts ...any) *MockTodoServiceHTTPClient_SyncTodos_Call {
	return &MockTodoServiceHTTPClient_SyncTodos_Call{Call: _e.mock.On("SyncTodos",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_SyncTodos_Call) Run(run func(ctx context.Context, opts ...http.CallOption)) *MockTodoServiceHTTPClient_SyncTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 1 {
			variadicArgs = args[1].([]http.CallOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_SyncTodos_Call) Return(v v1.TodoService_SyncTodosClient, err error) *MockTodoServiceHTTPClient_SyncTodos_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_SyncTodos_Call) RunAndReturn(run func(ctx context.Context, opts ...http.CallOption) (v1.TodoService_SyncTodosClient, error)) *MockTodoServiceHTTPClient_SyncTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) UpdateTodo(ctx context.Context, req *v1.UpdateTodoRequest, opts ...http.CallOption) (*v1.Todo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest, ...http.CallOption) (*v1.Todo, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest, ...http.CallOption) *v1.Todo); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.UpdateTodoRequest, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoServiceHTTPClient_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v1.UpdateTodoRequest
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) UpdateTodo(ctx any, req any, opts ...any) *MockTodoServiceHTTPClient_UpdateTodo_Call {
	return &MockTodoServiceHTTPClient_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_UpdateTodo_Call) Run(run func(ctx context.Context, req *v1.UpdateTodoRequest, opts ...http.CallOption)) *MockTodoServiceHTTPClient_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.UpdateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.UpdateTodoRequest)
		}
		var arg2 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]http.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_UpdateTodo_Call) Return(rsp *v1.Todo, err error) *MockTodoServiceHTTPClient_UpdateTodo_Call {
	_c.Call.Return(rsp, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, req *v1.UpdateTodoRequest, opts ...http.CallOption) (*v1.Todo, error)) *MockTodoServiceHTTPClient_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTodos provides a mock function for the type MockTodoServiceHTTPClient
func (_mock *MockTodoServiceHTTPClient) WatchTodos(ctx context.Context, req *v1.WatchTodosRequest, opts ...http.CallOption) (v1.TodoService_WatchTodosClient, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WatchTodos")
	}

	var r0 v1.TodoService_WatchTodosClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WatchTodosRequest, ...http.CallOption) (v1.TodoService_WatchTodosClient, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WatchTodosRequest, ...http.CallOption) v1.TodoService_WatchTodosClient); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.TodoService_WatchTodosClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.WatchTodosRequest, ...http.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPClient_WatchTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTodos'
type MockTodoServiceHTTPClient_WatchTodos_Call struct {
	*mock.Call
}

// WatchTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v1.WatchTodosRequest
//   - opts ...http.CallOption
func (_e *MockTodoServiceHTTPClient_Expecter) WatchTodos(ctx any, req any, opts ...any) *MockTodoServiceHTTPClient_WatchTodos_Call {
	return &MockTodoServiceHTTPClient_WatchTodos_Call{Call: _e.mock.On("WatchTodos",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockTodoServiceHTTPClient_WatchTodos_Call) Run(run func(ctx context.Context, req *v1.WatchTodosRequest, opts ...http.CallOption)) *MockTodoServiceHTTPClient_WatchTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.WatchTodosRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.WatchTodosRequest)
		}
		var arg2 []http.CallOption
		var variadicArgs []http.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]http.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPClient_WatchTodos_Call) Return(v v1.TodoService_WatchTodosClient, err error) *MockTodoServiceHTTPClient_WatchTodos_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTodoServiceHTTPClient_WatchTodos_Call) RunAndReturn(run func(ctx context.Context, req *v1.WatchTodosRequest, opts ...http.CallOption) (v1.TodoService_WatchTodosClient, error)) *MockTodoServiceHTTPClient_WatchTodos_Call {
	_c.Call.Return(run)
	return _c
}
