// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockTodoServiceClient creates a new instance of MockTodoServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoServiceClient {
	mock := &MockTodoServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoServiceClient is an autogenerated mock type for the TodoServiceClient type
type MockTodoServiceClient struct {
	mock.Mock
}

type MockTodoServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoServiceClient) EXPECT() *MockTodoServiceClient_Expecter {
	return &MockTodoServiceClient_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) CreateTodo(ctx context.Context, in *v1.CreateTodoRequest, opts ...grpc.CallOption) (*v1.Todo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest, ...grpc.CallOption) (*v1.Todo, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest, ...grpc.CallOption) *v1.Todo); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.CreateTodoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoServiceClient_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.CreateTodoRequest
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) CreateTodo(ctx any, in any, opts ...any) *MockTodoServiceClient_CreateTodo_Call {
	return &MockTodoServiceClient_CreateTodo_Call{Call: _e.mock.On("CreateTodo",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockTodoServiceClient_CreateTodo_Call) Run(run func(ctx context.Context, in *v1.CreateTodoRequest, opts ...grpc.CallOption)) *MockTodoServiceClient_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.CreateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.CreateTodoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_CreateTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceClient_CreateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceClient_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, in *v1.CreateTodoRequest, opts ...grpc.CallOption) (*v1.Todo, error)) *MockTodoServiceClient_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) DeleteTodo(ctx context.Context, in *v1.DeleteTodoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.DeleteTodoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoServiceClient_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.DeleteTodoRequest
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) DeleteTodo(ctx any, in any, opts ...any) *MockTodoServiceClient_DeleteTodo_Call {
	return &MockTodoServiceClient_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockTodoServiceClient_DeleteTodo_Call) Run(run func(ctx context.Context, in *v1.DeleteTodoRequest, opts ...grpc.CallOption)) *MockTodoServiceClient_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.DeleteTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.DeleteTodoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_DeleteTodo_Call) Return(empty *emptypb.Empty, err error) *MockTodoServiceClient_DeleteTodo_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockTodoServiceClient_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, in *v1.DeleteTodoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)) *MockTodoServiceClient_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) GetTodo(ctx context.Context, in *v1.GetTodoRequest, opts ...grpc.CallOption) (*v1.Todo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest, ...grpc.CallOption) (*v1.Todo, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest, ...grpc.CallOption) *v1.Todo); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.GetTodoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodoServiceClient_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.GetTodoRequest
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) GetTodo(ctx any, in any, opts ...any) *MockTodoServiceClient_GetTodo_Call {
	return &MockTodoServiceClient_GetTodo_Call{Call: _e.mock.On("GetTodo",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockTodoServiceClient_GetTodo_Call) Run(run func(ctx context.Context, in *v1.GetTodoRequest, opts ...grpc.CallOption)) *MockTodoServiceClient_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.GetTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.GetTodoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_GetTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceClient_GetTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceClient_GetTodo_Call) RunAndReturn(run func(ctx context.Context, in *v1.GetTodoRequest, opts ...grpc.CallOption) (*v1.Todo, error)) *MockTodoServiceClient_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) ListTodos(ctx context.Context, in *v1.ListTodosRequest, opts ...grpc.CallOption) (*v1.TodoSet, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 *v1.TodoSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest, ...grpc.CallOption) (*v1.TodoSet, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest, ...grpc.CallOption) *v1.TodoSet); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.TodoSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ListTodosRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoServiceClient_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ListTodosRequest
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) ListTodos(ctx any, in any, opts ...any) *MockTodoServiceClient_ListTodos_Call {
	return &MockTodoServiceClient_ListTodos_Call{Call: _e.mock.On("ListTodos",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockTodoServiceClient_ListTodos_Call) Run(run func(ctx context.Context, in *v1.ListTodosRequest, opts ...grpc.CallOption)) *MockTodoServiceClient_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ListTodosRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ListTodosRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_ListTodos_Call) Return(todoSet *v1.TodoSet, err error) *MockTodoServiceClient_ListTodos_Call {
	_c.Call.Return(todoSet, err)
	return _c
}

func (_c *MockTodoServiceClient_ListTodos_Call) RunAndReturn(run func(ctx context.Context, in *v1.ListTodosRequest, opts ...grpc.CallOption) (*v1.TodoSet, error)) *MockTodoServiceClient_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// SyncTodos provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) SyncTodos(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SyncTodos")
	}

	var r0 grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent], error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent]); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_SyncTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncTodos'
type MockTodoServiceClient_SyncTodos_Call struct {
	*mock.Call
}

// SyncTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) SyncTodos(ctx any, opts ...any) *MockTodoServiceClient_SyncTodos_Call {
	return &MockTodoServiceClient_SyncTodos_Call{Call: _e.mock.On("SyncTodos",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockTodoServiceClient_SyncTodos_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockTodoServiceClient_SyncTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 1 {
			variadicArgs = args[1].([]grpc.CallOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_SyncTodos_Call) Return(bidiStreamingClient grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent], err error) *MockTodoServiceClient_SyncTodos_Call {
	_c.Call.Return(bidiStreamingClient, err)
	return _c
}

func (_c *MockTodoServiceClient_SyncTodos_Call) RunAndReturn(run func(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.SyncTodoRequest, v1.TodoEvent], error)) *MockTodoServiceClient_SyncTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) UpdateTodo(ctx context.Context, in *v1.UpdateTodoRequest, opts ...grpc.CallOption) (*v1.Todo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest, ...grpc.CallOption) (*v1.Todo, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest, ...grpc.CallOption) *v1.Todo); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.UpdateTodoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoServiceClient_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.UpdateTodoRequest
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) UpdateTodo(ctx any, in any, opts ...any) *MockTodoServiceClient_UpdateTodo_Call {
	return &MockTodoServiceClient_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockTodoServiceClient_UpdateTodo_Call) Run(run func(ctx context.Context, in *v1.UpdateTodoRequest, opts ...grpc.CallOption)) *MockTodoServiceClient_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.UpdateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.UpdateTodoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_UpdateTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceClient_UpdateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceClient_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, in *v1.UpdateTodoRequest, opts ...grpc.CallOption) (*v1.Todo, error)) *MockTodoServiceClient_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTodos provides a mock function for the type MockTodoServiceClient
func (_mock *MockTodoServiceClient) WatchTodos(ctx context.Context, in *v1.WatchTodosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.TodoEvent], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WatchTodos")
	}

	var r0 grpc.ServerStreamingClient[v1.TodoEvent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WatchTodosRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[v1.TodoEvent], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WatchTodosRequest, ...grpc.CallOption) grpc.ServerStreamingClient[v1.TodoEvent]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[v1.TodoEvent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.WatchTodosRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceClient_WatchTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTodos'
type MockTodoServiceClient_WatchTodos_Call struct {
	*mock.Call
}

// WatchTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.WatchTodosRequest
//   - opts ...grpc.CallOption
func (_e *MockTodoServiceClient_Expecter) WatchTodos(ctx any, in any, opts ...any) *MockTodoServiceClient_WatchTodos_Call {
	return &MockTodoServiceClient_WatchTodos_Call{Call: _e.mock.On("WatchTodos",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockTodoServiceClient_WatchTodos_Call) Run(run func(ctx context.Context, in *v1.WatchTodosRequest, opts ...grpc.CallOption)) *MockTodoServiceClient_WatchTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.WatchTodosRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.WatchTodosRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTodoServiceClient_WatchTodos_Call) Return(serverStreamingClient grpc.ServerStreamingClient[v1.TodoEvent], err error) *MockTodoServiceClient_WatchTodos_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockTodoServiceClient_WatchTodos_Call) RunAndReturn(run func(ctx context.Context, in *v1.WatchTodosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.TodoEvent], error)) *MockTodoServiceClient_WatchTodos_Call {
	_c.Call.Return(run)
	return _c
}
