// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockTodoService_SyncTodosServer creates a new instance of MockTodoService_SyncTodosServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoService_SyncTodosServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoService_SyncTodosServer {
	mock := &MockTodoService_SyncTodosServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoService_SyncTodosServer is an autogenerated mock type for the TodoService_SyncTodosServer type
type MockTodoService_SyncTodosServer struct {
	mock.Mock
}

type MockTodoService_SyncTodosServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoService_SyncTodosServer) EXPECT() *MockTodoService_SyncTodosServer_Expecter {
	return &MockTodoService_SyncTodosServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockTodoService_SyncTodosServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockTodoService_SyncTodosServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosServer_Expecter) Context() *MockTodoService_SyncTodosServer_Context_Call {
	return &MockTodoService_SyncTodosServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockTodoService_SyncTodosServer_Context_Call) Run(run func()) *MockTodoService_SyncTodosServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_Context_Call) Return(context1 context.Context) *MockTodoService_SyncTodosServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_Context_Call) RunAndReturn(run func() context.Context) *MockTodoService_SyncTodosServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) Recv() (*v1.SyncTodoRequest, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *v1.SyncTodoRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*v1.SyncTodoRequest, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *v1.SyncTodoRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SyncTodoRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoService_SyncTodosServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockTodoService_SyncTodosServer_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockTodoService_SyncTodosServer_Expecter) Recv() *MockTodoService_SyncTodosServer_Recv_Call {
	return &MockTodoService_SyncTodosServer_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockTodoService_SyncTodosServer_Recv_Call) Run(run func()) *MockTodoService_SyncTodosServer_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_Recv_Call) Return(syncTodoRequest *v1.SyncTodoRequest, err error) *MockTodoService_SyncTodosServer_Recv_Call {
	_c.Call.Return(syncTodoRequest, err)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_Recv_Call) RunAndReturn(run func() (*v1.SyncTodoRequest, error)) *MockTodoService_SyncTodosServer_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockTodoService_SyncTodosServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockTodoService_SyncTodosServer_Expecter) RecvMsg(m any) *MockTodoService_SyncTodosServer_RecvMsg_Call {
	return &MockTodoService_SyncTodosServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockTodoService_SyncTodosServer_RecvMsg_Call) Run(run func(m any)) *MockTodoService_SyncTodosServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_RecvMsg_Call) Return(err error) *MockTodoService_SyncTodosServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockTodoService_SyncTodosServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) Send(todoEvent *v1.TodoEvent) error {
	ret := _mock.Called(todoEvent)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*v1.TodoEvent) error); ok {
		r0 = returnFunc(todoEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTodoService_SyncTodosServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - todoEvent *v1.TodoEvent
func (_e *MockTodoService_SyncTodosServer_Expecter) Send(todoEvent any) *MockTodoService_SyncTodosServer_Send_Call {
	return &MockTodoService_SyncTodosServer_Send_Call{Call: _e.mock.On("Send", todoEvent)}
}

func (_c *MockTodoService_SyncTodosServer_Send_Call) Run(run func(todoEvent *v1.TodoEvent)) *MockTodoService_SyncTodosServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.TodoEvent
		if args[0] != nil {
			arg0 = args[0].(*v1.TodoEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_Send_Call) Return(err error) *MockTodoService_SyncTodosServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_Send_Call) RunAndReturn(run func(todoEvent *v1.TodoEvent) error) *MockTodoService_SyncTodosServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockTodoService_SyncTodosServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockTodoService_SyncTodosServer_Expecter) SendHeader(mD any) *MockTodoService_SyncTodosServer_SendHeader_Call {
	return &MockTodoService_SyncTodosServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockTodoService_SyncTodosServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockTodoService_SyncTodosServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SendHeader_Call) Return(err error) *MockTodoService_SyncTodosServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockTodoService_SyncTodosServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockTodoService_SyncTodosServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockTodoService_SyncTodosServer_Expecter) SendMsg(m any) *MockTodoService_SyncTodosServer_SendMsg_Call {
	return &MockTodoService_SyncTodosServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockTodoService_SyncTodosServer_SendMsg_Call) Run(run func(m any)) *MockTodoService_SyncTodosServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SendMsg_Call) Return(err error) *MockTodoService_SyncTodosServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockTodoService_SyncTodosServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoService_SyncTodosServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockTodoService_SyncTodosServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockTodoService_SyncTodosServer_Expecter) SetHeader(mD any) *MockTodoService_SyncTodosServer_SetHeader_Call {
	return &MockTodoService_SyncTodosServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockTodoService_SyncTodosServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockTodoService_SyncTodosServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SetHeader_Call) Return(err error) *MockTodoService_SyncTodosServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockTodoService_SyncTodosServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockTodoService_SyncTodosServer
func (_mock *MockTodoService_SyncTodosServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockTodoService_SyncTodosServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockTodoService_SyncTodosServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockTodoService_SyncTodosServer_Expecter) SetTrailer(mD any) *MockTodoService_SyncTodosServer_SetTrailer_Call {
	return &MockTodoService_SyncTodosServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockTodoService_SyncTodosServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockTodoService_SyncTodosServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SetTrailer_Call) Return() *MockTodoService_SyncTodosServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTodoService_SyncTodosServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockTodoService_SyncTodosServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
