// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockTodoServiceServer creates a new instance of MockTodoServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoServiceServer {
	mock := &MockTodoServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoServiceServer is an autogenerated mock type for the TodoServiceServer type
type MockTodoServiceServer struct {
	mock.Mock
}

type MockTodoServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoServiceServer) EXPECT() *MockTodoServiceServer_Expecter {
	return &MockTodoServiceServer_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) CreateTodo(context1 context.Context, createTodoRequest *v1.CreateTodoRequest) (*v1.Todo, error) {
	ret := _mock.Called(context1, createTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest) (*v1.Todo, error)); ok {
		return returnFunc(context1, createTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest) *v1.Todo); ok {
		r0 = returnFunc(context1, createTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.CreateTodoRequest) error); ok {
		r1 = returnFunc(context1, createTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceServer_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoServiceServer_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - createTodoRequest *v1.CreateTodoRequest
func (_e *MockTodoServiceServer_Expecter) CreateTodo(context1 any, createTodoRequest any) *MockTodoServiceServer_CreateTodo_Call {
	return &MockTodoServiceServer_CreateTodo_Call{Call: _e.mock.On("CreateTodo", context1, createTodoRequest)}
}

func (_c *MockTodoServiceServer_CreateTodo_Call) Run(run func(context1 context.Context, createTodoRequest *v1.CreateTodoRequest)) *MockTodoServiceServer_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.CreateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.CreateTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_CreateTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceServer_CreateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceServer_CreateTodo_Call) RunAndReturn(run func(context1 context.Context, createTodoRequest *v1.CreateTodoRequest) (*v1.Todo, error)) *MockTodoServiceServer_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) DeleteTodo(context1 context.Context, deleteTodoRequest *v1.DeleteTodoRequest) (*emptypb.Empty, error) {
	ret := _mock.Called(context1, deleteTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest) (*emptypb.Empty, error)); ok {
		return returnFunc(context1, deleteTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest) *emptypb.Empty); ok {
		r0 = returnFunc(context1, deleteTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.DeleteTodoRequest) error); ok {
		r1 = returnFunc(context1, deleteTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceServer_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoServiceServer_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteTodoRequest *v1.DeleteTodoRequest
func (_e *MockTodoServiceServer_Expecter) DeleteTodo(context1 any, deleteTodoRequest any) *MockTodoServiceServer_DeleteTodo_Call {
	return &MockTodoServiceServer_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", context1, deleteTodoRequest)}
}

func (_c *MockTodoServiceServer_DeleteTodo_Call) Run(run func(context1 context.Context, deleteTodoRequest *v1.DeleteTodoRequest)) *MockTodoServiceServer_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.DeleteTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.DeleteTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_DeleteTodo_Call) Return(empty *emptypb.Empty, err error) *MockTodoServiceServer_DeleteTodo_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockTodoServiceServer_DeleteTodo_Call) RunAndReturn(run func(context1 context.Context, deleteTodoRequest *v1.DeleteTodoRequest) (*emptypb.Empty, error)) *MockTodoServiceServer_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) GetTodo(context1 context.Context, getTodoRequest *v1.GetTodoRequest) (*v1.Todo, error) {
	ret := _mock.Called(context1, getTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest) (*v1.Todo, error)); ok {
		return returnFunc(context1, getTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest) *v1.Todo); ok {
		r0 = returnFunc(context1, getTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.GetTodoRequest) error); ok {
		r1 = returnFunc(context1, getTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceServer_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodoServiceServer_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - getTodoRequest *v1.GetTodoRequest
func (_e *MockTodoServiceServer_Expecter) GetTodo(context1 any, getTodoRequest any) *MockTodoServiceServer_GetTodo_Call {
	return &MockTodoServiceServer_GetTodo_Call{Call: _e.mock.On("GetTodo", context1, getTodoRequest)}
}

func (_c *MockTodoServiceServer_GetTodo_Call) Run(run func(context1 context.Context, getTodoRequest *v1.GetTodoRequest)) *MockTodoServiceServer_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.GetTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.GetTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_GetTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceServer_GetTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceServer_GetTodo_Call) RunAndReturn(run func(context1 context.Context, getTodoRequest *v1.GetTodoRequest) (*v1.Todo, error)) *MockTodoServiceServer_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) ListTodos(context1 context.Context, listTodosRequest *v1.ListTodosRequest) (*v1.TodoSet, error) {
	ret := _mock.Called(context1, listTodosRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 *v1.TodoSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest) (*v1.TodoSet, error)); ok {
		return returnFunc(context1, listTodosRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest) *v1.TodoSet); ok {
		r0 = returnFunc(context1, listTodosRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.TodoSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ListTodosRequest) error); ok {
		r1 = returnFunc(context1, listTodosRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceServer_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoServiceServer_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - context1 context.Context
//   - listTodosRequest *v1.ListTodosRequest
func (_e *MockTodoServiceServer_Expecter) ListTodos(context1 any, listTodosRequest any) *MockTodoServiceServer_ListTodos_Call {
	return &MockTodoServiceServer_ListTodos_Call{Call: _e.mock.On("ListTodos", context1, listTodosRequest)}
}

func (_c *MockTodoServiceServer_ListTodos_Call) Run(run func(context1 context.Context, listTodosRequest *v1.ListTodosRequest)) *MockTodoServiceServer_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ListTodosRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ListTodosRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_ListTodos_Call) Return(todoSet *v1.TodoSet, err error) *MockTodoServiceServer_ListTodos_Call {
	_c.Call.Return(todoSet, err)
	return _c
}

func (_c *MockTodoServiceServer_ListTodos_Call) RunAndReturn(run func(context1 context.Context, listTodosRequest *v1.ListTodosRequest) (*v1.TodoSet, error)) *MockTodoServiceServer_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// SyncTodos provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) SyncTodos(bidiStreamingServer grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent]) error {
	ret := _mock.Called(bidiStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for SyncTodos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent]) error); ok {
		r0 = returnFunc(bidiStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoServiceServer_SyncTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncTodos'
type MockTodoServiceServer_SyncTodos_Call struct {
	*mock.Call
}

// SyncTodos is a helper method to define mock.On call
//   - bidiStreamingServer grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent]
func (_e *MockTodoServiceServer_Expecter) SyncTodos(bidiStreamingServer any) *MockTodoServiceServer_SyncTodos_Call {
	return &MockTodoServiceServer_SyncTodos_Call{Call: _e.mock.On("SyncTodos", bidiStreamingServer)}
}

func (_c *MockTodoServiceServer_SyncTodos_Call) Run(run func(bidiStreamingServer grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent])) *MockTodoServiceServer_SyncTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent]
		if args[0] != nil {
			arg0 = args[0].(grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_SyncTodos_Call) Return(err error) *MockTodoServiceServer_SyncTodos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoServiceServer_SyncTodos_Call) RunAndReturn(run func(bidiStreamingServer grpc.BidiStreamingServer[v1.SyncTodoRequest, v1.TodoEvent]) error) *MockTodoServiceServer_SyncTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) UpdateTodo(context1 context.Context, updateTodoRequest *v1.UpdateTodoRequest) (*v1.Todo, error) {
	ret := _mock.Called(context1, updateTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest) (*v1.Todo, error)); ok {
		return returnFunc(context1, updateTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest) *v1.Todo); ok {
		r0 = returnFunc(context1, updateTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.UpdateTodoRequest) error); ok {
		r1 = returnFunc(context1, updateTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceServer_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoServiceServer_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - updateTodoRequest *v1.UpdateTodoRequest
func (_e *MockTodoServiceServer_Expecter) UpdateTodo(context1 any, updateTodoRequest any) *MockTodoServiceServer_UpdateTodo_Call {
	return &MockTodoServiceServer_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", context1, updateTodoRequest)}
}

func (_c *MockTodoServiceServer_UpdateTodo_Call) Run(run func(context1 context.Context, updateTodoRequest *v1.UpdateTodoRequest)) *MockTodoServiceServer_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.UpdateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.UpdateTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_UpdateTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceServer_UpdateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceServer_UpdateTodo_Call) RunAndReturn(run func(context1 context.Context, updateTodoRequest *v1.UpdateTodoRequest) (*v1.Todo, error)) *MockTodoServiceServer_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTodos provides a mock function for the type MockTodoServiceServer
func (_mock *MockTodoServiceServer) WatchTodos(watchTodosRequest *v1.WatchTodosRequest, serverStreamingServer grpc.ServerStreamingServer[v1.TodoEvent]) error {
	ret := _mock.Called(watchTodosRequest, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for WatchTodos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*v1.WatchTodosRequest, grpc.ServerStreamingServer[v1.TodoEvent]) error); ok {
		r0 = returnFunc(watchTodosRequest, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoServiceServer_WatchTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTodos'
type MockTodoServiceServer_WatchTodos_Call struct {
	*mock.Call
}

// WatchTodos is a helper method to define mock.On call
//   - watchTodosRequest *v1.WatchTodosRequest
//   - serverStreamingServer grpc.ServerStreamingServer[v1.TodoEvent]
func (_e *MockTodoServiceServer_Expecter) WatchTodos(watchTodosRequest any, serverStreamingServer any) *MockTodoServiceServer_WatchTodos_Call {
	return &MockTodoServiceServer_WatchTodos_Call{Call: _e.mock.On("WatchTodos", watchTodosRequest, serverStreamingServer)}
}

func (_c *MockTodoServiceServer_WatchTodos_Call) Run(run func(watchTodosRequest *v1.WatchTodosRequest, serverStreamingServer grpc.ServerStreamingServer[v1.TodoEvent])) *MockTodoServiceServer_WatchTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.WatchTodosRequest
		if args[0] != nil {
			arg0 = args[0].(*v1.WatchTodosRequest)
		}
		var arg1 grpc.ServerStreamingServer[v1.TodoEvent]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[v1.TodoEvent])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceServer_WatchTodos_Call) Return(err error) *MockTodoServiceServer_WatchTodos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoServiceServer_WatchTodos_Call) RunAndReturn(run func(watchTodosRequest *v1.WatchTodosRequest, serverStreamingServer grpc.ServerStreamingServer[v1.TodoEvent]) error) *MockTodoServiceServer_WatchTodos_Call {
	_c.Call.Return(run)
	return _c
}
