// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1mock

import (
	"context"

	"github.com/kkhnifes/kratos-layout/api/todo/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockTodoServiceHTTPServer creates a new instance of MockTodoServiceHTTPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoServiceHTTPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoServiceHTTPServer {
	mock := &MockTodoServiceHTTPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoServiceHTTPServer is an autogenerated mock type for the TodoServiceHTTPServer type
type MockTodoServiceHTTPServer struct {
	mock.Mock
}

type MockTodoServiceHTTPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoServiceHTTPServer) EXPECT() *MockTodoServiceHTTPServer_Expecter {
	return &MockTodoServiceHTTPServer_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) CreateTodo(context1 context.Context, createTodoRequest *v1.CreateTodoRequest) (*v1.Todo, error) {
	ret := _mock.Called(context1, createTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest) (*v1.Todo, error)); ok {
		return returnFunc(context1, createTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CreateTodoRequest) *v1.Todo); ok {
		r0 = returnFunc(context1, createTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.CreateTodoRequest) error); ok {
		r1 = returnFunc(context1, createTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPServer_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoServiceHTTPServer_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - createTodoRequest *v1.CreateTodoRequest
func (_e *MockTodoServiceHTTPServer_Expecter) CreateTodo(context1 any, createTodoRequest any) *MockTodoServiceHTTPServer_CreateTodo_Call {
	return &MockTodoServiceHTTPServer_CreateTodo_Call{Call: _e.mock.On("CreateTodo", context1, createTodoRequest)}
}

func (_c *MockTodoServiceHTTPServer_CreateTodo_Call) Run(run func(context1 context.Context, createTodoRequest *v1.CreateTodoRequest)) *MockTodoServiceHTTPServer_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.CreateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.CreateTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_CreateTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceHTTPServer_CreateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_CreateTodo_Call) RunAndReturn(run func(context1 context.Context, createTodoRequest *v1.CreateTodoRequest) (*v1.Todo, error)) *MockTodoServiceHTTPServer_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) DeleteTodo(context1 context.Context, deleteTodoRequest *v1.DeleteTodoRequest) (*emptypb.Empty, error) {
	ret := _mock.Called(context1, deleteTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest) (*emptypb.Empty, error)); ok {
		return returnFunc(context1, deleteTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteTodoRequest) *emptypb.Empty); ok {
		r0 = returnFunc(context1, deleteTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.DeleteTodoRequest) error); ok {
		r1 = returnFunc(context1, deleteTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPServer_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoServiceHTTPServer_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteTodoRequest *v1.DeleteTodoRequest
func (_e *MockTodoServiceHTTPServer_Expecter) DeleteTodo(context1 any, deleteTodoRequest any) *MockTodoServiceHTTPServer_DeleteTodo_Call {
	return &MockTodoServiceHTTPServer_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", context1, deleteTodoRequest)}
}

func (_c *MockTodoServiceHTTPServer_DeleteTodo_Call) Run(run func(context1 context.Context, deleteTodoRequest *v1.DeleteTodoRequest)) *MockTodoServiceHTTPServer_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.DeleteTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.DeleteTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_DeleteTodo_Call) Return(empty *emptypb.Empty, err error) *MockTodoServiceHTTPServer_DeleteTodo_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_DeleteTodo_Call) RunAndReturn(run func(context1 context.Context, deleteTodoRequest *v1.DeleteTodoRequest) (*emptypb.Empty, error)) *MockTodoServiceHTTPServer_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) GetTodo(context1 context.Context, getTodoRequest *v1.GetTodoRequest) (*v1.Todo, error) {
	ret := _mock.Called(context1, getTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest) (*v1.Todo, error)); ok {
		return returnFunc(context1, getTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.GetTodoRequest) *v1.Todo); ok {
		r0 = returnFunc(context1, getTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.GetTodoRequest) error); ok {
		r1 = returnFunc(context1, getTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPServer_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodoServiceHTTPServer_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - getTodoRequest *v1.GetTodoRequest
func (_e *MockTodoServiceHTTPServer_Expecter) GetTodo(context1 any, getTodoRequest any) *MockTodoServiceHTTPServer_GetTodo_Call {
	return &MockTodoServiceHTTPServer_GetTodo_Call{Call: _e.mock.On("GetTodo", context1, getTodoRequest)}
}

func (_c *MockTodoServiceHTTPServer_GetTodo_Call) Run(run func(context1 context.Context, getTodoRequest *v1.GetTodoRequest)) *MockTodoServiceHTTPServer_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.GetTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.GetTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_GetTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceHTTPServer_GetTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_GetTodo_Call) RunAndReturn(run func(context1 context.Context, getTodoRequest *v1.GetTodoRequest) (*v1.Todo, error)) *MockTodoServiceHTTPServer_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) ListTodos(context1 context.Context, listTodosRequest *v1.ListTodosRequest) (*v1.TodoSet, error) {
	ret := _mock.Called(context1, listTodosRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 *v1.TodoSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest) (*v1.TodoSet, error)); ok {
		return returnFunc(context1, listTodosRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ListTodosRequest) *v1.TodoSet); ok {
		r0 = returnFunc(context1, listTodosRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.TodoSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ListTodosRequest) error); ok {
		r1 = returnFunc(context1, listTodosRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPServer_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoServiceHTTPServer_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - context1 context.Context
//   - listTodosRequest *v1.ListTodosRequest
func (_e *MockTodoServiceHTTPServer_Expecter) ListTodos(context1 any, listTodosRequest any) *MockTodoServiceHTTPServer_ListTodos_Call {
	return &MockTodoServiceHTTPServer_ListTodos_Call{Call: _e.mock.On("ListTodos", context1, listTodosRequest)}
}

func (_c *MockTodoServiceHTTPServer_ListTodos_Call) Run(run func(context1 context.Context, listTodosRequest *v1.ListTodosRequest)) *MockTodoServiceHTTPServer_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ListTodosRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ListTodosRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_ListTodos_Call) Return(todoSet *v1.TodoSet, err error) *MockTodoServiceHTTPServer_ListTodos_Call {
	_c.Call.Return(todoSet, err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_ListTodos_Call) RunAndReturn(run func(context1 context.Context, listTodosRequest *v1.ListTodosRequest) (*v1.TodoSet, error)) *MockTodoServiceHTTPServer_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// SyncTodos provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) SyncTodos(v v1.TodoService_SyncTodosServer) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for SyncTodos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1.TodoService_SyncTodosServer) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoServiceHTTPServer_SyncTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncTodos'
type MockTodoServiceHTTPServer_SyncTodos_Call struct {
	*mock.Call
}

// SyncTodos is a helper method to define mock.On call
//   - v v1.TodoService_SyncTodosServer
func (_e *MockTodoServiceHTTPServer_Expecter) SyncTodos(v any) *MockTodoServiceHTTPServer_SyncTodos_Call {
	return &MockTodoServiceHTTPServer_SyncTodos_Call{Call: _e.mock.On("SyncTodos", v)}
}

func (_c *MockTodoServiceHTTPServer_SyncTodos_Call) Run(run func(v v1.TodoService_SyncTodosServer)) *MockTodoServiceHTTPServer_SyncTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1.TodoService_SyncTodosServer
		if args[0] != nil {
			arg0 = args[0].(v1.TodoService_SyncTodosServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_SyncTodos_Call) Return(err error) *MockTodoServiceHTTPServer_SyncTodos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_SyncTodos_Call) RunAndReturn(run func(v v1.TodoService_SyncTodosServer) error) *MockTodoServiceHTTPServer_SyncTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) UpdateTodo(context1 context.Context, updateTodoRequest *v1.UpdateTodoRequest) (*v1.Todo, error) {
	ret := _mock.Called(context1, updateTodoRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *v1.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest) (*v1.Todo, error)); ok {
		return returnFunc(context1, updateTodoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.UpdateTodoRequest) *v1.Todo); ok {
		r0 = returnFunc(context1, updateTodoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.UpdateTodoRequest) error); ok {
		r1 = returnFunc(context1, updateTodoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoServiceHTTPServer_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoServiceHTTPServer_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - context1 context.Context
//   - updateTodoRequest *v1.UpdateTodoRequest
func (_e *MockTodoServiceHTTPServer_Expecter) UpdateTodo(context1 any, updateTodoRequest any) *MockTodoServiceHTTPServer_UpdateTodo_Call {
	return &MockTodoServiceHTTPServer_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", context1, updateTodoRequest)}
}

func (_c *MockTodoServiceHTTPServer_UpdateTodo_Call) Run(run func(context1 context.Context, updateTodoRequest *v1.UpdateTodoRequest)) *MockTodoServiceHTTPServer_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.UpdateTodoRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.UpdateTodoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_UpdateTodo_Call) Return(todo *v1.Todo, err error) *MockTodoServiceHTTPServer_UpdateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_UpdateTodo_Call) RunAndReturn(run func(context1 context.Context, updateTodoRequest *v1.UpdateTodoRequest) (*v1.Todo, error)) *MockTodoServiceHTTPServer_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTodos provides a mock function for the type MockTodoServiceHTTPServer
func (_mock *MockTodoServiceHTTPServer) WatchTodos(watchTodosRequest *v1.WatchTodosRequest, v v1.TodoService_WatchTodosServer) error {
	ret := _mock.Called(watchTodosRequest, v)

	if len(ret) == 0 {
		panic("no return value specified for WatchTodos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*v1.WatchTodosRequest, v1.TodoService_WatchTodosServer) error); ok {
		r0 = returnFunc(watchTodosRequest, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoServiceHTTPServer_WatchTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTodos'
type MockTodoServiceHTTPServer_WatchTodos_Call struct {
	*mock.Call
}

// WatchTodos is a helper method to define mock.On call
//   - watchTodosRequest *v1.WatchTodosRequest
//   - v v1.TodoService_WatchTodosServer
func (_e *MockTodoServiceHTTPServer_Expecter) WatchTodos(watchTodosRequest any, v any) *MockTodoServiceHTTPServer_WatchTodos_Call {
	return &MockTodoServiceHTTPServer_WatchTodos_Call{Call: _e.mock.On("WatchTodos", watchTodosRequest, v)}
}

func (_c *MockTodoServiceHTTPServer_WatchTodos_Call) Run(run func(watchTodosRequest *v1.WatchTodosRequest, v v1.TodoService_WatchTodosServer)) *MockTodoServiceHTTPServer_WatchTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.WatchTodosRequest
		if args[0] != nil {
			arg0 = args[0].(*v1.WatchTodosRequest)
		}
		var arg1 v1.TodoService_WatchTodosServer
		if args[1] != nil {
			arg1 = args[1].(v1.TodoService_WatchTodosServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoServiceHTTPServer_WatchTodos_Call) Return(err error) *MockTodoServiceHTTPServer_WatchTodos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoServiceHTTPServer_WatchTodos_Call) RunAndReturn(run func(watchTodosRequest *v1.WatchTodosRequest, v v1.TodoService_WatchTodosServer) error) *MockTodoServiceHTTPServer_WatchTodos_Call {
	_c.Call.Return(run)
	return _c
}
